### ISSUE TITLE
Request: Adjusting Eco Gear max. speed?

### ISSUE THREAD

**Issue by JRGaarde** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#10]
Thanks for freeing our scooters :)

Setting the speed to Unlimited, the Gears seem to be set to the following max. speed:
**P1/Eco = 15 km/h**
P2/Drive = 25 km/h
P3/Sport = Unlimited

Would it be possible to change the max. speed of the **Eco gear** to 20 km/h, iow.:
**P1/Eco = 20 km/h**
P2/Drive = 25 km/h
P3/Sport = Unlimited

This would make it possible to use the Eco gear to maintain the legal max speed during inner city travels, without having to keep an eye on the speedometer.

**Comment by skybluesdan** [comment]
I agree :)

**Comment by BenjaminSoelberg** [comment]
Everything is possible.  But the speed steps is currently located in the firmware on the scooter. And this patch merely sends a value between 0 and 4 to select the predefined speed step in the scooter. Hence the app isn't really directly selecting the top speed but merely a max speed step. This can only be fixed by changing the firmware itself and not by patching the app. So currently no, sorry. But I definitely understand the inconvenience.

**Comment by Aasikki** [comment]
Maybe you could use the cruise control as a workaround, if there's not too much obstructions on the way preventing you maintaining the speed? Personally I wouldn't really worry much about going 5 over the limit, but it's definitely understandable if you don't want to do that.
