### ISSUE TITLE
Tyre Size

### ISSUE THREAD

**Issue by marcomunter** [BenjaminSoelberg/wilfa-e-way-electric-scooter-hack#7]
Hi! 

Would it be possible to add an option to change tyre change in this app? I'v updates 10 inch wheels on mine and they are the best, but the speedometer shows invorrect speed and it also effects to scooters efficiency kinda a lot. Thanks for your response. 

Marco

**Comment by BenjaminSoelberg** [comment]
- [ ] Congrats on your new upgrade. In principle a compensation factor could be added to the app. But a discrepancy would then exists between the scooter display and the app as the scooter runs the main software and relays the information back to the phone via Bluetooth. So the right place to make such changes would be in the scooter firmware and not in the app. The app is what I have patched and not the firmware. Again patching the firmware is possible but it is an entirely different beast. Also I have merely patch the existing app rather than implemented new features. The latter is 10 fold more difficult as we don't have access to the actual source and build system. But feel free to give it a go as it is possible to do so if you have a lot of free time on your hand. I would fully support the journey. 

Have a great day.
